export const classes = {
  container: "space-y-4",
  uuid: "text-gray-90 text-s1 font-semibold",
  metaRow: "text-gray-90 text-b4 font-medium",
  metaValue: "text-gray-70 text-b4 font-regular",
  divider: "border-t border-gray-30 my-4",
  breakdownBox: "ml-auto w-56 space-y-2",
  breakdownRow: "flex items-center justify-between text-b4",
  breakdownLabel: "text-gray-70 text-c2 font-medium",
  breakdownValue: "text-right text-gray-70 text-c2 font-regular",
  emptyState: "text-gray-70 text-b3",
  actionsRow: "flex items-center gap-2",
  commentLink: "mt-2 inline-flex items-center gap-2 text-blue-60 text-label font-medium",
  commentIcon: "h-4 w-4 text-blue-60",
  commentBoxPadding: "pt-4",
};
export const mobileclasses = {
  container: "space-y-4",
  uuid: "text-gray-90 text-b2 font-semibold",
  metaRow: "text-gray-90 text-c2 font-medium",
  metaValue: "text-gray-70 text-c2 font-regular",
  divider: "border-t border-gray-30 my-4",
  breakdownBox: "ml-auto w-44 space-y-2",
  breakdownRow: "flex items-center justify-between text-b4",
  breakdownLabel: "text-gray-70 text-c2 font-medium",
  breakdownValue: "text-right text-gray-70 text-c2 font-regular",
  emptyState: "text-gray-70 text-b3",
  actionsRow: "flex items-center gap-2",
  commentLink: "mt-2 inline-flex items-center gap-2 text-blue-60 text-label font-medium",
  commentIcon: "h-4 w-4 text-blue-60",
  commentBoxPadding: "pt-4",
};
