import { StyleSheet } from '@react-pdf/renderer';

import {
  PDF_CONTENT_PADDING_BOTTOM,
  PDF_CONTENT_PADDING_LEFT,
  PDF_CONTENT_PADDING_RIGHT,
  PDF_CONTENT_PADDING_TOP,
  PDF_IMAGE_CARD_HEIGHT,
  PDF_IMAGE_CARD_WIDTH,
  PDF_IMAGE_ROW_GAP,
} from './layout';

export const styles = StyleSheet.create({
  page: {
    fontSize: 8,
    fontFamily: 'Mechanical',
  },
  content: {
    paddingTop: PDF_CONTENT_PADDING_TOP,
    paddingRight: PDF_CONTENT_PADDING_RIGHT,
    paddingBottom: PDF_CONTENT_PADDING_BOTTOM,
    paddingLeft: PDF_CONTENT_PADDING_LEFT,
  },
  section: {},
  tableHeader: {
    backgroundColor: '#001E2F',
    padding: 5,
    fontWeight: 'bold',
    textAlign: 'center',
    color: 'white',
  },
  flexRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginBottom: 1,
  },
  cell: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
    width: '48%',
  },
  fullWidthCell: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  labelText: {
    fontWeight: 'bold',
    marginRight: 5,
    backgroundColor: '#e0e0e0',
    padding: 2,
    flexShrink: 0,
  },
  text: {
    flex: 1,
    margin: 5,
  },
  titleText: {
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 65,
  },
  watermark: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageContainer: {
    display: 'flex',
    flexDirection: 'column',
  },
  imageRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: PDF_IMAGE_ROW_GAP,
  },
  imageCard: {
    display: 'flex',
    alignItems: 'center',
    border: '1px solid #e0e0e0',
    padding: 0,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 0,
    width: PDF_IMAGE_CARD_WIDTH,
  },
  imageTitle: {
    fontSize: 9,
    marginBottom: 5,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  imageDescription: {
    width: '100%',
    minHeight: 30,
    maxHeight: 50,
    fontSize: 8,
    backgroundColor: '#e0e0e0',
    textAlign: 'center',
    overflow: 'hidden',
    padding: 2,
  },
  imageStyle: {
    width: PDF_IMAGE_CARD_WIDTH,
    height: PDF_IMAGE_CARD_HEIGHT,
    objectFit: 'contain',
    marginBottom: 0,
  },
  signatureContainer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  signatureBox: {
    width: '23%',
    padding: 10,
    textAlign: 'center',
    marginBottom: 10,
    border: '1px solid #e0e0e0',
  },
  signatureImage: {
    width: '100%',
    height: 40,
    objectFit: 'contain',
    marginBottom: 5,
    alignSelf: 'center',
  },
  signatureLine: {
    width: '100%',
    height: 1,
    backgroundColor: '#000',
    marginVertical: 5,
  },
  signatureName: {
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 5,
  },
  signatureCharge: {
    fontSize: 9,
    marginTop: 5,
  },
  progressBarContainer: {
    width: '30%',
    backgroundColor: '#e0e0e0',
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
    marginLeft: '40px',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#001E2F',
  },
  folioText: {
    fontSize: 9,
    fontWeight: 'bold',
    marginRight: '40px',
    marginTop: '55px',
    textAlign: 'right',
  },
  progressText: {
    fontSize: 9,
    marginLeft: '40px',
    marginBottom: 5,
  },
  footer: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
    textAlign: 'right',
    fontSize: 8,
    marginRight: '35px',
    fontWeight: 'light',
    opacity: 0.5,
  },
  pageNumber: {
    position: 'absolute',
    bottom: 10,
    left: 35,
    fontSize: 8,
    color: 'white',
  },
  tableContainer: {
    marginVertical: 10,
  },
  tableHeaders: {
    backgroundColor: '#001E2F',
    color: '#FFFFFF',
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 5,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingVertical: 1,
  },
  tableCell: {
    padding: 5,
    fontSize: 8,
    textAlign: 'center',
    flex: 1,
  },
  headerCell: {
    fontWeight: 'bold',
  },
  listItemContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 2,
  },
  listBullet: {
    width: 10,
    fontSize: 10,
  },
  listItemText: {
    flex: 1,
    fontSize: 8,
    marginLeft: 5,
  },
  headerBox: {
    position: 'absolute',
    top: 20,
    right: 35,
    width: 240,
    borderWidth: 1,
    borderColor: '#001E2F',
    borderStyle: 'solid',
    padding: 4,
  },
  headerBoxRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  headerBoxRowSingle: {
    marginBottom: 2,
  },
  headerBoxTitle: {
    fontWeight: 'bold',
    fontSize: 8,
  },
  headerBoxText: {
    fontSize: 8,
  },
  folioTextBelow: {
    position: 'absolute',
    top: 90,
    right: 35,
    fontSize: 9,
    fontWeight: 'bold',
    color: '#001E2F',
  },
});
