import type { TutorialDefinition } from '../types';

export const mainPageTutorials: TutorialDefinition[] = [
  {
    id: 'main-page:theme-toggle',
    moduleId: 'main-page',
    title: 'Recorrido de la página principal',
    description: 'Conoce las secciones y acciones clave del panel principal.',
    version: 2,
    steps: [
      {
        target: '[data-tour="mobile-menu-button"]',
        title: 'Menú principal (móvil)',
        description: 'En móvil, abre el menú lateral desde aquí.',
        onlyMobile: true,
      },
      {
        target: '[data-tour="sidebar-nav"]',
        title: 'Módulos disponibles',
        description: 'Aquí encuentras los módulos a los que tiene acceso tu usuario.',
        sidebar: 'open',
        popoverSide: 'right',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="main-content"]',
        title: 'Contenido del módulo',
        description: 'En esta sección se muestra el contenido del módulo seleccionado.',
        sidebar: 'close',
        popoverSide: 'top',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="main-tabs"]',
        title: 'Navegación superior',
        description: 'Estas pestañas te ayudan a moverte entre secciones del módulo.',
        popoverSide: 'bottom',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="notifications-bell"]',
        title: 'Notificaciones',
        description: 'Consulta tus notificaciones pendientes desde la campanita.',
        popoverSide: 'bottom',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="help-button"]',
        title: 'Centro de tutoriales',
        description: 'Desde aquí puedes volver a ver los tutoriales cuando quieras.',
        popoverSide: 'bottom',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="offline-toggle"]',
        title: 'Modo offline',
        description: 'Activa o desactiva el modo sin conexión cuando sea necesario.',
        sidebar: 'open',
        popoverSide: 'right',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="theme-toggle"]',
        title: 'Cambiar tema',
        description: 'Alterna entre modo claro y oscuro según tu preferencia.',
        sidebar: 'open',
        popoverSide: 'right',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="theme-toggle"]',
        title: 'Preferencia guardada',
        description: 'Tu elección se guarda y se aplica automáticamente en futuras visitas.',
        sidebar: 'open',
        popoverSide: 'right',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="configuration-button"]',
        title: 'Configuración',
        description: 'Administra tu perfil y preferencias desde aquí.',
        sidebar: 'open',
        popoverSide: 'right',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="sidebar-help-link"]',
        title: 'Ayuda',
        description: 'Accede a la mesa de ayuda y recursos de soporte.',
        sidebar: 'open',
        popoverSide: 'right',
        popoverAlign: 'center',
      },
      {
        target: '[data-tour="logout-button"]',
        title: 'Cerrar sesión',
        description: 'Finaliza tu sesión de forma segura cuando termines.',
        sidebar: 'open',
        popoverSide: 'right',
        popoverAlign: 'center',
      },
    ],
  },
];
