/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      boxShadow: {
        100: "0px 1px 2px rgba(0, 0, 0, 0.04)",
        200: "0px 1px 3px rgba(0, 0, 0, 0.06)",
        300: "0px 2px 4px rgba(0, 0, 0, 0.08)",
        400: "0px 4px 6px rgba(0, 0, 0, 0.10)",
        500: "0px 6px 10px rgba(0, 0, 0, 0.12)",
        600: "0px 8px 14px rgba(0, 0, 0, 0.14)",
        700: "0px 10px 20px rgba(0, 0, 0, 0.16)",
        800: "0px 12px 24px rgba(0, 0, 0, 0.18)",
      },
      borderRadius: {
        "3xl": "1.5rem",
        "2xl": "1rem",
        xl: "0.75rem",
        lg: "0.625rem",
        md: "0.5rem",
        sm: "0.375rem",
        xs: "0.25rem",
      },
      spacing: {
        "btn-giant-x": "1.5rem", // padding horizontal
        "btn-giant-y": "1rem", // padding vertical
        "btn-large-x": "1.25rem",
        "btn-large-y": "0.75rem",
        "btn-md-x": "1rem",
        "btn-md-y": "0.5rem",
        "btn-sm-x": "0.75rem",
        "btn-sm-y": "0.375rem",
        "btn-xs-x": "0.5rem",
        "btn-xs-y": "0.25rem",
      },
      fontFamily: {
        sans: [
          "var(--font-plus-jakarta)",
          "var(--font-montserrat)",
          "sans-serif",
        ],
        display: [
          "var(--font-nulshock)",
          "var(--font-plus-jakarta)",
          "var(--font-montserrat)",
          "sans-serif",
        ],
        outfit: [
          "var(--font-outfit)",
          "sans-serif",
        ]
      },
      fontWeight: {
        regular: 400,
        medium: 500,
        semibold: 600,
      },
      fontSize: {
        "btn-giant": ["18px", { lineHeight: "24px" }],
        "btn-large": ["16px", { lineHeight: "20px" }],
        "btn-md": ["14px", { lineHeight: "16px" }],
        "btn-sm": ["12px", { lineHeight: "16px" }],
        "btn-xs": ["10px", { lineHeight: "12px" }],
        h1: ["48px", { lineHeight: "58px" }],
        h2: ["40px", { lineHeight: "48px" }],
        h3: ["32px", { lineHeight: "38px" }],
        h4: ["28px", { lineHeight: "34px" }],
        h5: ["24px", { lineHeight: "28px" }],
        s1: ["18px", { lineHeight: "28px" }],
        s2: ["16px", { lineHeight: "24px" }],
        b1: ["16px", { lineHeight: "24px" }],
        b2: ["16px", { lineHeight: "24px" }],
        b3: ["14px", { lineHeight: "20px" }],
        b4: ["14px", { lineHeight: "20px" }],
        c1: ["12px", { lineHeight: "16px" }],
        c2: ["12px", { lineHeight: "16px" }],
        c3: ["10px", { lineHeight: "14px" }],
        d3: ["10px", { lineHeight: "14px" }],
        d4: ["8px", { lineHeight: "14px" }],
        label: ["12px", { lineHeight: "16px" }],
        labelm: ["10px", { lineHeight: "14px" }],
        "cta-giant": ["18px", { lineHeight: "24px" }],
        "cta-large": ["16px", { lineHeight: "20px" }],
        "cta-md": ["14px", { lineHeight: "16px" }],
        "cta-sm": ["12px", { lineHeight: "16px" }],
        "cta-xs": ["10px", { lineHeight: "12px" }],
      },
      colors: {
        black: {
          100: "var(--color-black-100)",
          90: "var(--color-black-90)",
          80: "var(--color-black-80)",
          70: "var(--color-black-70)",
          60: "var(--color-black-60)",
          50: "var(--color-black-50)",
          40: "var(--color-black-40)",
          30: "var(--color-black-30)",
          20: "var(--color-black-20)",
          10: "var(--color-black-10)",
        },

        white: {
          100: "var(--color-white-100)",
          90: "var(--color-white-90)",
          80: "var(--color-white-80)",
          70: "var(--color-white-70)",
          60: "var(--color-white-60)",
          50: "var(--color-white-50)",
          40: "var(--color-white-40)",
          30: "var(--color-white-30)",
          20: "var(--color-white-20)",
          10: "var(--color-white-10)",
        },
        blue: {
          100: "var(--color-blue-100)",
          90: "var(--color-blue-90)",
          80: "var(--color-blue-80)",
          70: "var(--color-blue-70)",
          60: "var(--color-blue-60)",
          50: "var(--color-blue-50)",
          40: "var(--color-blue-40)",
          30: "var(--color-blue-30)",
          20: "var(--color-blue-20)",
          10: "var(--color-blue-10)",
        },
        green: {
          100: "var(--color-green-100)",
          90: "var(--color-green-90)",
          80: "var(--color-green-80)",
          70: "var(--color-green-70)",
          60: "var(--color-green-60)",
          50: "var(--color-green-50)",
          40: "var(--color-green-40)",
          30: "var(--color-green-30)",
          20: "var(--color-green-20)",
          10: "var(--color-green-10)",
        },
        turquoise: {
          100: "var(--color-turquoise-100)",
          90: "var(--color-turquoise-90)",
          80: "var(--color-turquoise-80)",
          70: "var(--color-turquoise-70)",
          60: "var(--color-turquoise-60)",
          50: "var(--color-turquoise-50)",
          40: "var(--color-turquoise-40)",
          30: "var(--color-turquoise-30)",
          20: "var(--color-turquoise-20)",
          10: "var(--color-turquoise-10)",
        },
        gray: {
          100: "var(--color-gray-100)",
          90: "var(--color-gray-90)",
          80: "var(--color-gray-80)",
          70: "var(--color-gray-70)",
          60: "var(--color-gray-60)",
          50: "var(--color-gray-50)",
          40: "var(--color-gray-40)",
          30: "var(--color-gray-30)",
          20: "var(--color-gray-20)",
          10: "var(--color-gray-10)",
        },
        "alert-purple": {
          100: "var(--color-alert-purple-100)",
          50: "var(--color-alert-purple-50)",
          10: "var(--color-alert-purple-10)",
        },
        "alert-pink": {
          100: "var(--color-alert-pink-100)",
          50: "var(--color-alert-pink-50)",
          10: "var(--color-alert-pink-10)",
        },
        "alert-green": {
          100: "var(--color-alert-green-100)",
          50: "var(--color-alert-green-50)",
          10: "var(--color-alert-green-10)",
        },
        "alert-yellow": {
          100: "var(--color-alert-yellow-100)",
          50: "var(--color-alert-yellow-50)",
          10: "var(--color-alert-yellow-10)",
        },
        "alert-red": {
          100: "var(--color-alert-red-100)",
          50: "var(--color-alert-red-50)",
          10: "var(--color-alert-red-10)",
        },
        "alert-orange": {
          100: "var(--color-alert-orange-100)",
          50: "var(--color-alert-orange-50)",
          10: "var(--color-alert-orange-10)",
        },
        "alert-blue": {
          900: "var(--color-alert-blue-900)",
          100: "var(--color-alert-blue-100)",
          50: "var(--color-alert-blue-50)",
          10: "var(--color-alert-blue-10)",
        },
      },
    },
  },
  plugins: [],
};
