import type { PendingUserDetailData, PendingUserRow } from './types'

export const MOCK_PENDING_USERS: PendingUserRow[] = [
  {
    id: '30000',
    fullname: 'Tania Guerrero',
    department: 'Desarrollo',
    position: 'Lead Desarrollo',
    employeeNumber: '30000',
    hasFingerprint: true,
  },
  {
    id: '30001',
    fullname: 'Luis Lopez',
    department: 'Recursos Humanos',
    position: 'Puesto de Recursos Humanos',
    employeeNumber: '30001',
    hasFingerprint: false,
  },
  {
    id: '30002',
    fullname: 'Mariana Soto',
    department: 'Compras',
    position: 'Coordinadora de Compras',
    employeeNumber: '30002',
    hasFingerprint: true,
  },
  {
    id: '30003',
    fullname: 'Luis Velazco',
    department: 'Almacen',
    position: 'Puesto de Almacen',
    employeeNumber: '30003',
    hasFingerprint: false,
  },
]

export const MOCK_PENDING_USER_DETAILS: Record<string, PendingUserDetailData> = {
  '30000': {
    ...MOCK_PENDING_USERS[0],
    avatarUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=320&q=80',
    company: 'ITEDESCA',
    firstName: 'Tania',
    middleName: 'Fabiola',
    lastName: 'Guerrero',
    secondLastName: 'Peralta',
    managerName: 'Roberto Rafael Gómez Pérez',
    departmentLabel: 'Desarrollo',
    companyLabel: 'ITEDESCA',
    positionLabel: 'Diseñadora UI/UX',
    email: 'tania.guerrero@drsecurity.net',
    businessPhone: '55 5555 2200',
    userRoleId: 'designer',
    roleName: 'Diseñadora',
    changePasswordOnNextLogin: true,
    managerialPermissions: true,
    deviceType: 'Laptop',
    deviceBrand: 'Dell',
    deviceModel: 'XPS 15 9520',
    deviceStatus: 'Óptimo',
    provisionalPassword: '********',
    nip: '1234',
  },
  '30001': {
    ...MOCK_PENDING_USERS[1],
    avatarUrl:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=320&q=80',
    company: 'DR Security',
    firstName: 'Luis',
    middleName: 'Alberto',
    lastName: 'Lopez',
    secondLastName: 'Mendez',
    managerName: 'Carolina Reyes Torres',
    departmentLabel: 'Recursos Humanos',
    companyLabel: 'DR Security',
    positionLabel: 'Especialista RH',
    email: 'luis.lopez@drsecurity.net',
    businessPhone: '55 2222 1000',
    userRoleId: 'rh-supervisor',
    roleName: 'Supervisor RH',
    changePasswordOnNextLogin: false,
    managerialPermissions: true,
    deviceType: 'Laptop',
    deviceBrand: 'Lenovo',
    deviceModel: 'ThinkPad E14',
    deviceStatus: 'Óptimo',
    provisionalPassword: '********',
    nip: '4455',
  },
  '30002': {
    ...MOCK_PENDING_USERS[2],
    avatarUrl:
      'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=320&q=80',
    company: 'ITEDESCA',
    firstName: 'Mariana',
    middleName: 'Guadalupe',
    lastName: 'Soto',
    secondLastName: 'Ramírez',
    managerName: 'Laura Delgado Mejía',
    departmentLabel: 'Compras',
    companyLabel: 'ITEDESCA',
    positionLabel: 'Coordinadora de Compras',
    email: 'mariana.soto@drsecurity.net',
    businessPhone: '55 1010 2020',
    userRoleId: 'compras',
    roleName: 'Compras',
    changePasswordOnNextLogin: true,
    managerialPermissions: false,
    deviceType: 'Celular',
    deviceBrand: 'Apple',
    deviceModel: 'iPhone 13',
    deviceStatus: 'Óptimo',
    provisionalPassword: '********',
    nip: '7788',
  },
  '30003': {
    ...MOCK_PENDING_USERS[3],
    company: 'DR Security',
    firstName: 'Luis',
    middleName: 'Antonio',
    lastName: 'Velazco',
    secondLastName: 'Pérez',
    managerName: 'Jorge Contreras Ríos',
    departmentLabel: 'Almacen',
    companyLabel: 'DR Security',
    positionLabel: 'Auxiliar de Almacén',
    email: 'luis.velazco@drsecurity.net',
    businessPhone: '55 4400 8899',
    userRoleId: 'warehouse',
    roleName: 'Almacén',
    changePasswordOnNextLogin: false,
    managerialPermissions: false,
    deviceType: 'Laptop',
    deviceBrand: 'HP',
    deviceModel: 'ProBook 440',
    deviceStatus: 'En revisión',
    provisionalPassword: '********',
    nip: '9900',
  },
}
