export const preRequisitionStyles = {
  container: 'space-y-4 text-gray-80',
  header: 'flex flex-wrap items-center justify-between gap-4',
  titleWrap: 'flex min-w-[260px] flex-1 items-center gap-3',
  title: 'text-b3 text-blue-60',
  divider: 'hidden h-px flex-1 bg-blue-40 md:block',
  actions: 'flex items-center gap-3',
  summaryCard: 'rounded-lg bg-white-100 px-5 py-4 shadow-200',
  fieldsGrid: 'grid gap-x-8 gap-y-3 sm:grid-cols-2 lg:grid-cols-4',
  fieldLabel: 'mb-1 block text-c2 text-gray-60',
  fieldValue:
    'flex h-9 w-full items-center rounded-md border border-gray-30 bg-gray-10 px-3 text-c2 text-gray-70',
  collaborators: 'mt-3 text-c2 text-blue-60',
  tableCard: 'overflow-hidden rounded-lg bg-white-100 px-5 py-4 shadow-200',
  tableWrap: 'overflow-x-auto',
  table: 'min-w-[860px] w-full border-collapse text-c2',
  tableHead:
    'border-b border-blue-30 text-[10px] font-semibold uppercase text-blue-80',
  headerCell: 'px-3 py-3 text-center align-bottom',
  conceptHeaderCell: 'px-3 py-3 text-left align-bottom',
  bodyRow: 'border-b border-gray-10 last:border-b-0',
  conceptCell: 'px-3 py-2 text-left text-gray-70',
  numberCell: 'px-3 py-2 text-center text-gray-60',
  observationCell: 'px-3 py-2 text-left text-gray-60',
  totalsWrap: 'mt-3 flex justify-end',
  totals: 'w-full max-w-[360px] space-y-1 text-c2 text-gray-80',
  totalLine: 'grid grid-cols-[1fr_auto] gap-8',
  hint: 'text-gray-50',
  note: 'mt-3 text-[10px] leading-4 text-blue-60',
}
