import type { ReportView } from '@/app/mappings/reports/reports.types';

export const createEmptyReport = (): ReportView => ({
  id: '',
  model: {
    maps: false,
    diagnostic: false,
    solution: false,
    refactions: false,
    clientsign: false,
    ticket: false,
  },
  startdate: '',
  enddate: '',
  datecreate: '',
  proyect: {
    id: '',
    name: '',
    proyectKey: '',
    client: '',
    collaborators: [],
  } as any,
  type: '',
  reportcategories: {
    id: '',
    name: '',
    typesofreports: { id: '', name: '', description: '' },
  },
  location: {} as any,
  employe: {} as any,
  workposition: {} as any,
  remarks: '',
  progress: '0',
  ticket: '',
  employeesignurl: '',
  activities: [],
  maps: [],
  diagnostic: '',
  solution: '',
  idSpareParts: [],
  refactions: [],
  clientsign: {},
  front_identifier: '',
  reportDeviceView: [],
});
