export const classes = {
container: "flex flex-col space-y-4",
uuid: "text-gray-90 text-s1 font-semibold",
labelLine: "text-gray-90 text-b4 font-medium",
valueText: "text-gray-90 text-b3 font-regular",
sectionTopMargin: "mt-4",
conceptsScroller: "mt-4 pr-2 space-y-4",
conceptItem: "space-y-1",
sapRowsContainer: "space-y-4",
sapRow: "grid grid-cols-1 md:grid-cols-[1fr_260px] gap-4 items-center",
sapSelectBox: "w-full",
expenseTypeRow: "grid grid-cols-1 md:grid-cols-[1fr_260px] gap-4 items-center",
expenseTypeLabel: "text-gray-90 text-b4 font-medium",
expenseTable: "space-y-2",
expenseHeaderRow: "grid grid-cols-4 gap-4 border-b border-gray-30 pb-2",
expenseHeader: "text-gray-90 text-b3 font-medium",
expenseDataRow: "grid grid-cols-4 gap-4",
expenseCell: "text-gray-90 text-b3 font-regular truncate",
divider: "border-t border-gray-30 my-4",
breakdownBox: "flex flex-col ml-auto w-50 space-y-1",
breakdownRow: "flex items-center justify-between text-b4",
breakdownLabel: "text-gray-90 text-b4 font-medium",
breakdownValue: "text-right text-gray-90 text-b3 font-regular",
emptyState: "text-gray-70 text-b3",
actionsRow: "flex items-center gap-2",
commentBoxPadding: "pt-4",
requisitionkey:"text-gray-90 text-b4 font-medium",
requisitionkeyspan:"text-gray-90 text-b3 font-regular",
editInformationBox:"m-0 flex items-center justify-between gap-3",
bottomSection: "space-y-4",
satRowsContainer: "space-y-5 pr-3",
satItemBlock: "border-b border-[#7BA9C9] pb-5 last:border-b-0 last:pb-0",
satItemContent: "space-y-2",
satLine: "grid grid-cols-[128px_minmax(0,1fr)] items-center gap-x-3 gap-y-1",
satLineLabel: "text-gray-90 text-c1 font-medium tracking-[0.01em]",
satLineValue: "text-gray-90 text-c2 font-regular",
satDescriptionValue: "text-gray-90 text-c1 font-regular leading-5",
satDescriptionEditorContainer: "w-full",
satDescriptionEditor: "min-h-[88px] rounded-xl border-gray-30 bg-white-100 px-3 py-2 text-c2 text-gray-90",
satRightField: "w-full max-w-[188px] justify-self-end",
satRightFieldStack: "w-full max-w-[188px] justify-self-end space-y-0",
satFieldCaption: "text-gray-60 text-[11px] font-medium leading-4",
currencyField: "relative",
currencyPrefix: "pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-gray-90 text-c2 font-medium",
moneyInput: "h-8 rounded-xl border-gray-30 bg-white-100 pl-7 pr-3 py-0 text-c2 text-gray-90",
readonlyMoneyInput: "h-8 rounded-xl border-gray-30 bg-gray-10 pl-7 pr-3 py-0 text-c2 text-gray-60",
readonlyInput: "h-8 rounded-xl border-gray-30 bg-gray-10 py-0 text-c2 text-gray-60",
sapSelectTrigger: "h-8 rounded-xl border-gray-30 bg-white-100 text-c2 text-gray-90 py-0 min-h-0 [&>span:first-child]:truncate [&>span:first-child]:whitespace-nowrap [&>span:first-child]:overflow-hidden",
breakdownBoxCompact: "flex flex-col ml-auto w-fit min-w-[210px] space-y-0"
};
export const mobileclasses = {
container: "flex flex-col space-y-4",
uuid: "text-gray-90 text-b2 font-semibold",
labelLine: "text-gray-90 text-c2 font-medium",
valueText: "text-gray-90 text-c2 font-regular",
sectionTopMargin: "mt-4",
conceptsScroller: "mt-4 pr-2 space-y-4",
conceptItem: "space-y-1",
sapRowsContainer: "space-y-4",
sapRow: "space-y-2",
sapSelectBox: "w-full",
expenseTypeRow: "space-y-2",
expenseTypeLabel: "text-gray-90 text-c2 font-medium",
expenseTable: "space-y-2",
expenseHeaderRow: "grid grid-cols-2 gap-2 border-b border-gray-30 pb-2",
expenseHeader: "text-gray-90 text-c2 font-medium",
expenseDataRow: "grid grid-cols-2 gap-2",
expenseCell: "text-gray-90 text-c2 font-regular",
divider: "border-t border-gray-30 my-4",
breakdownBox: "ml-auto w-50 space-y-1",
breakdownRow: "flex items-center justify-between text-b4",
breakdownLabel: "text-gray-90 text-c2 font-medium",
breakdownValue: "text-right text-gray-90 text-b3 font-regular",
emptyState: "text-gray-70 text-b3",
actionsRow: "flex items-center gap-2",
commentBoxPadding: "pt-4",
requisitionkey:"text-blue-60 text-label font-medium",
requisitionkeyspan:"text-blue-60 text-label font-regular",
satRowsContainer: "space-y-5 pr-1",
satItemBlock: "border-b border-[#7BA9C9] pb-5 last:border-b-0 last:pb-0",
satItemContent: "space-y-2",
satLine: "grid grid-cols-1 gap-1.5",
satLineLabel: "text-gray-90 text-c1 font-medium tracking-[0.02em]",
satLineValue: "text-gray-90 text-c2 font-regular",
satDescriptionValue: "text-gray-90 text-c1 font-regular leading-5",
satDescriptionEditorContainer: "w-full",
satDescriptionEditor: "min-h-[88px] rounded-xl border-gray-30 bg-white-100 px-3 py-2 text-c2 text-gray-90",
satRightField: "w-full",
satRightFieldStack: "w-full space-y-0",
satFieldCaption: "text-gray-60 text-[11px] font-medium leading-4",
currencyField: "relative",
currencyPrefix: "pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-gray-90 text-c2 font-medium",
moneyInput: "h-8 rounded-xl border-gray-30 bg-white-100 pl-7 pr-3 py-0 text-c2 text-gray-90",
readonlyMoneyInput: "h-8 rounded-xl border-gray-30 bg-gray-10 pl-7 pr-3 py-0 text-c2 text-gray-60",
readonlyInput: "h-8 rounded-xl border-gray-30 bg-gray-10 py-0 text-c2 text-gray-60",
sapSelectTrigger: "h-8 rounded-xl border-gray-30 bg-white-100 text-c2 text-gray-90 py-0 min-h-0 [&>span:first-child]:truncate [&>span:first-child]:whitespace-nowrap [&>span:first-child]:overflow-hidden",
breakdownBoxCompact: "ml-auto w-full max-w-[230px] space-y-0"
};
