export const classes = {
container: "flex h-full min-h-0 flex-col space-y-4",
uuid: "text-gray-90 text-s1 font-semibold",
labelLine: "text-gray-90 text-b4 font-medium",
valueText: "text-gray-90 text-b3 font-regular",
sectionTopMargin: "mt-4",
conceptsScroller: "mt-4 flex-1 min-h-0 overflow-y-auto pr-2 space-y-4",
conceptItem: "space-y-1",
sapRowsContainer: "space-y-4",
sapRow: "grid grid-cols-1 md:grid-cols-[1fr_260px] gap-4 items-center",
sapSelectBox: "w-full",
expenseTable: "space-y-2",
expenseHeaderRow: "grid grid-cols-4 gap-4 border-b border-gray-30 pb-2",
expenseHeader: "text-gray-90 text-b3 font-medium",
expenseDataRow: "grid grid-cols-4 gap-4",
expenseCell: "text-gray-90 text-b3 font-regular truncate",
divider: "border-t border-gray-30 my-4",
breakdownBox: "flex flex-col ml-auto w-50 space-y-1",
breakdownRow: "flex items-center justify-between text-b4",
breakdownLabel: "text-gray-90 text-b4 font-medium",
breakdownValue: "text-right text-gray-90 text-b3 font-regular",
emptyState: "text-gray-70 text-b3",
actionsRow: "flex items-center gap-2",
commentBoxPadding: "pt-4",
requisitionkey:"text-gray-90 text-b4 font-medium",
requisitionkeyspan:"text-gray-90 text-b3 font-regular",
editInformationBox:"flex justify-end",
bottomSection: "mt-auto space-y-4"
};
export const mobileclasses = {
container: "flex h-full min-h-0 flex-col space-y-4",
uuid: "text-gray-90 text-b2 font-semibold",
labelLine: "text-gray-90 text-c2 font-medium",
valueText: "text-gray-90 text-c2 font-regular",
sectionTopMargin: "mt-4",
conceptsScroller: "mt-4 flex-1 min-h-0 overflow-y-auto pr-2 space-y-4",
conceptItem: "space-y-1",
sapRowsContainer: "space-y-4",
sapRow: "space-y-2",
sapSelectBox: "w-full",
expenseTable: "space-y-2",
expenseHeaderRow: "grid grid-cols-2 gap-2 border-b border-gray-30 pb-2",
expenseHeader: "text-gray-90 text-c2 font-medium",
expenseDataRow: "grid grid-cols-2 gap-2",
expenseCell: "text-gray-90 text-c2 font-regular",
divider: "border-t border-gray-30 my-4",
breakdownBox: "ml-auto w-50 space-y-1",
breakdownRow: "flex items-center justify-between text-b4",
breakdownLabel: "text-gray-90 text-c2 font-medium",
breakdownValue: "text-right text-gray-90 text-b3 font-regular",
emptyState: "text-gray-70 text-b3",
actionsRow: "flex items-center gap-2",
commentBoxPadding: "pt-4",
requisitionkey:"text-blue-60 text-label font-medium",
requisitionkeyspan:"text-blue-60 text-label font-regular",
bottomSection: "mt-auto space-y-4"
};
