import type { ActivatedUserRow, UserAccountDetailData } from './types'

export const MOCK_USERS: ActivatedUserRow[] = [
  {
    id: '30000',
    fullname: 'Rafael Gomez',
    department: 'Desarrollo',
    position: 'Lead Desarrollo',
    employeeNumber: '30000',
    isActive: true,
    hasFingerprint: true,
  },
  {
    id: '30001',
    fullname: 'Luis Lopez',
    department: 'Recursos Humanos',
    position: 'Puesto de Recursos Humanos',
    employeeNumber: '30001',
    isActive: true,
    hasFingerprint: true,
  },
  {
    id: '30002',
    fullname: 'Tania Guerrero',
    department: 'Desarrollo',
    position: 'Puesto de Desarrollo',
    employeeNumber: '30002',
    isActive: true,
    hasFingerprint: true,
  },
  {
    id: '30003',
    fullname: 'Luis Velazco',
    department: 'Almacen',
    position: 'Puesto de Almacen',
    employeeNumber: '30003',
    isActive: false,
    hasFingerprint: false,
  },
  {
    id: '30004',
    fullname: 'Andrea Ruiz',
    department: 'Finanzas',
    position: 'Analista de Tesoreria',
    employeeNumber: '30004',
    isActive: true,
    hasFingerprint: false,
  },
  {
    id: '30005',
    fullname: 'Carlos Mendez',
    department: 'Operaciones',
    position: 'Supervisor Regional',
    employeeNumber: '30005',
    isActive: false,
    hasFingerprint: true,
  },
  {
    id: '30006',
    fullname: 'Mariana Soto',
    department: 'Compras',
    position: 'Coordinadora de Compras',
    employeeNumber: '30006',
    isActive: true,
    hasFingerprint: true,
  },
  {
    id: '30007',
    fullname: 'Ernesto Lara',
    department: 'IT',
    position: 'Administrador de Sistemas',
    employeeNumber: '30007',
    isActive: true,
    hasFingerprint: false,
  },
]

export const MOCK_USER_DETAILS: Record<string, UserAccountDetailData> = {
  '30000': {
    ...MOCK_USERS[0],
    userId: 'user-30000',
    company: 'ITEDESCA',
    statusLabel: 'Activo',
    avatarUrl:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=140&q=80',
    username: 'rafa.gomez',
    userRoleId: 'admin',
    twoFactorEnabled: true,
    changePasswordOnNextLogin: false,
    managerialPermissions: true,
    businessPhone: '55 5555 5555',
    provisionalPassword: '************',
    phone: 'No phone',
    email: 'rafa.gomez@drsecurity.net',
    roleName: 'Admin',
    departmentLabel: 'Desarrollo tecnológico',
    positionLabel: 'Ingeniero de software',
    assignedDevices: [
      { id: '1', typeLabel: 'TELÉFONO', description: 'Samsung 1923hp' },
      { id: '2', typeLabel: 'COMPUTADORA', description: 'DELL 1839jks' },
    ],
  },
  '30001': {
    ...MOCK_USERS[1],
    userId: 'user-30001',
    company: 'DR Security',
    statusLabel: 'Activo',
    avatarUrl:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=140&q=80',
    username: 'luis.lopez',
    userRoleId: 'rh-supervisor',
    twoFactorEnabled: true,
    changePasswordOnNextLogin: true,
    managerialPermissions: true,
    businessPhone: '55 1234 1234',
    provisionalPassword: '************',
    phone: '55 1234 1234',
    email: 'luis.lopez@drsecurity.net',
    roleName: 'Supervisor RH',
    departmentLabel: 'Recursos Humanos',
    positionLabel: 'Puesto de Recursos Humanos',
    assignedDevices: [
      { id: '1', typeLabel: 'TELÉFONO', description: 'iPhone 14 Pro' },
      { id: '2', typeLabel: 'COMPUTADORA', description: 'Latitude 5440' },
    ],
  },
  '30002': {
    ...MOCK_USERS[2],
    userId: 'user-30002',
    company: 'ITEDESCA',
    statusLabel: 'Activo',
    username: 'tania.guerrero',
    userRoleId: 'editor',
    twoFactorEnabled: false,
    changePasswordOnNextLogin: false,
    managerialPermissions: false,
    businessPhone: '55 9988 7766',
    provisionalPassword: '************',
    phone: '55 9988 7766',
    email: 'tania.guerrero@drsecurity.net',
    roleName: 'Editor',
    departmentLabel: 'Desarrollo',
    positionLabel: 'Puesto de Desarrollo',
    assignedDevices: [
      { id: '1', typeLabel: 'TELÉFONO', description: 'Pixel 7' },
      { id: '2', typeLabel: 'COMPUTADORA', description: 'MacBook Air M2' },
    ],
  },
  '30003': {
    ...MOCK_USERS[3],
    userId: 'user-30003',
    company: 'DR Security',
    statusLabel: 'Desactivado',
    username: 'luis.velazco',
    userRoleId: 'viewer',
    twoFactorEnabled: false,
    changePasswordOnNextLogin: false,
    managerialPermissions: false,
    businessPhone: '55 2200 4455',
    provisionalPassword: '************',
    phone: '55 2200 4455',
    email: 'luis.velazco@drsecurity.net',
    roleName: 'Invitado',
    departmentLabel: 'Almacen',
    positionLabel: 'Puesto de Almacen',
    assignedDevices: [
      { id: '1', typeLabel: 'TELÉFONO', description: 'Moto G84' },
      { id: '2', typeLabel: 'COMPUTADORA', description: 'HP ProBook' },
    ],
  },
  '30004': {
    ...MOCK_USERS[4],
    userId: 'user-30004',
    company: 'ITEDESCA',
    statusLabel: 'Activo',
    avatarUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=140&q=80',
    username: 'andrea.ruiz',
    userRoleId: 'analyst',
    twoFactorEnabled: true,
    changePasswordOnNextLogin: false,
    managerialPermissions: false,
    businessPhone: '55 3344 1122',
    provisionalPassword: '************',
    phone: '55 3344 1122',
    email: 'andrea.ruiz@drsecurity.net',
    roleName: 'Analista',
    departmentLabel: 'Finanzas',
    positionLabel: 'Analista de Tesoreria',
    assignedDevices: [
      { id: '1', typeLabel: 'TELÉFONO', description: 'Galaxy A54' },
      { id: '2', typeLabel: 'COMPUTADORA', description: 'ThinkPad E14' },
    ],
  },
  '30005': {
    ...MOCK_USERS[5],
    userId: 'user-30005',
    company: 'DR Security',
    statusLabel: 'Desactivado',
    username: 'carlos.mendez',
    userRoleId: 'supervisor',
    twoFactorEnabled: false,
    changePasswordOnNextLogin: true,
    managerialPermissions: true,
    businessPhone: '55 6677 9900',
    provisionalPassword: '************',
    phone: '55 6677 9900',
    email: 'carlos.mendez@drsecurity.net',
    roleName: 'Supervisor',
    departmentLabel: 'Operaciones',
    positionLabel: 'Supervisor Regional',
    assignedDevices: [
      { id: '1', typeLabel: 'TELÉFONO', description: 'Nokia XR20' },
      { id: '2', typeLabel: 'COMPUTADORA', description: 'EliteBook 845' },
    ],
  },
  '30006': {
    ...MOCK_USERS[6],
    userId: 'user-30006',
    company: 'ITEDESCA',
    statusLabel: 'Activo',
    avatarUrl:
      'https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=140&q=80',
    username: 'mariana.soto',
    userRoleId: 'compras',
    twoFactorEnabled: true,
    changePasswordOnNextLogin: false,
    managerialPermissions: false,
    businessPhone: '55 1010 2020',
    provisionalPassword: '************',
    phone: '55 1010 2020',
    email: 'mariana.soto@drsecurity.net',
    roleName: 'Compras',
    departmentLabel: 'Compras',
    positionLabel: 'Coordinadora de Compras',
    assignedDevices: [
      { id: '1', typeLabel: 'TELÉFONO', description: 'iPhone 13' },
      { id: '2', typeLabel: 'COMPUTADORA', description: 'Inspiron 15' },
    ],
  },
  '30007': {
    ...MOCK_USERS[7],
    userId: 'user-30007',
    company: 'DR Security',
    statusLabel: 'Activo',
    username: 'ernesto.lara',
    userRoleId: 'it-admin',
    twoFactorEnabled: true,
    changePasswordOnNextLogin: true,
    managerialPermissions: true,
    businessPhone: '55 7788 6655',
    provisionalPassword: '************',
    phone: '55 7788 6655',
    email: 'ernesto.lara@drsecurity.net',
    roleName: 'Administrador',
    departmentLabel: 'IT',
    positionLabel: 'Administrador de Sistemas',
    assignedDevices: [
      { id: '1', typeLabel: 'TELÉFONO', description: 'Nothing Phone 2' },
      { id: '2', typeLabel: 'COMPUTADORA', description: 'ROG Zephyrus' },
    ],
  },
}
