export const departmentsStyles = {
  container: "relative flex min-h-[calc(100vh-180px)] flex-col gap-6",
  searchRow: "flex w-full items-center mt-[4px] w-[380px]",
  searchWrapper: "w-full max-w-[380px] mt-[20px]",
  searchInput: "w-[380px]",
  viewToggle: "flex items-center",
  viewButton:
    "flex h-9 w-9 items-center justify-center rounded-md border border-gray-30 text-gray-70 transition-colors hover:border-blue-40 hover:text-blue-70",
  viewButtonActive: "border-blue-60 text-blue-70 shadow-200",
  listGrid: "flex flex-wrap gap-4",
  sectionHeader: "flex items-center gap-4 text-b3 text-blue-70",
  sectionDivider: "h-[0.5px] flex-1 bg-blue-60",
  listCard: "w-full rounded-xl bg-white-100 shadow-200 px-5 py-4",
  listColumns: "",
  listRow: "flex justify-between",
  listRowAvatar: "",
  listInfo: "flex flex-col gap-2",
  listLink: "text-green-100 hover:text-blue-80 text-c2",
  listLinkData: "text-gray-70 text-b2",
  mosaicGrid: "flex flex-wrap gap-4",
  mosaicCard: "flex w-[314px] gap-4 rounded-xl bg-white-100 shadow-200",
  listAvatar: "flex h-[92px] w-[92px] items-center overflow-hidden rounded-xl",
  mosaicAvatar:
    "flex h-auto w-[100px] items-center overflow-hidden",
  mosaicInfo: "flex flex-1 flex-col gap-1 text-b3 text-gray-90 p-[16px] pl-0",
  mosaicCompany: "text-c2 uppercase text-gray-60",
  mosaicName: "text-s2 font-semibold text-green-90",
  mosaicRole: "text-d3 text-gray-70",
  mosaicMeta: "text-d3 text-gray-70",
  emptyState: "bg-white-100 text-b3 text-gray-70 shadow-200 rounded-lg p-6",
  errorState:
    "bg-alert-red-10 text-b3 text-alert-red-100 shadow-200 rounded-lg p-6",
  pagination: "mt-auto flex w-full justify-center pt-2",
};
