export const calendarStyles = {
  calendarContainer: "calendar-container relative",
  triggerBtn: "calendar-icon p-1 rounded-[10px] transition-all",
  triggerDisabled: "opacity-40 cursor-not-allowed",
  triggerHover: "bg-green-10",
  trigerFocus: "ring-2 focus:ring-green-40 focus:outline-none",
  subCalendarContainer: "absolute left-50 top-0 bg-white p-4 shadow-lg rounded-md z-50 w-[400px] ml-5",
  subCalendarMobile: "absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-50 bg-white p-4 rounded shadow-md w-[90%] max-w-md",
  subCalendarTitle: "text-center text-sm text-blue-60",
  subCalendarWrapper: "flex justify-between mt-3",
  wrapper: "w-[140px]",
  inputWrapper: "flex items-center mt-3",
  inputLabel: "text-gray-70 text-label w-[40px] mr-2",
  input: "border rounded px-2 py-1 w-[90px] bg-gray-10 border-none",
  buttonWrapper: "flex justify-center",
  button: "bg-green-80 text-white rounded px-4 py-1 mt-2 w-full",
  modalOverlay: "fixed inset-0 bg-[#002A4133] bg-opacity-50 z-40 flex items-center justify-center",
};
